[package]
name = "mlr-rs"
version = "0.1.0"
authors = ["Paul Adenot <paul@paul.cx>"]

[dependencies]
audrey = "0.2.0"
monome-rs = "0.1.2"
log = "0.4.2"
pretty_env_logger = "0.2.3"
cubeb = "0.5.2"
timer = "0.2"
chrono = "0.4"
audio-clock = "0.2.0"
